replicaCount: 1

image:
  repository: mohanadnassar/mohanad-portfolio
  pullPolicy: Always
  tag: latest1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /dennis
  hosts:
    - host: mohanad-portfolio.com
      paths:
        - path: /dennis
          pathType: Prefix
  tls: []

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
