replicas: 3

image:
  repository: mohanadnassar/mohanad-portfolio
  tag: latest

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
