replicaCount: 1
image:
  repository: mohanadnassar/mohanad-portfolio
  pullPolicy: Always
  tag: latest
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mohanad-portfolio.com
      paths:
        - path: /
          pathType: Prefix
tls: []
