apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mohanad-portfolio
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/MohanadNasar/Mohanad-Portfolio
  ref:
    branch: main
