apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: flux-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mohanad-portfolio
    meta.helm.sh/release-namespace: flux-system  
stringData:
  token: 
