apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mohanad-portfolio
  namespace: flux-system  
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mohanad-portfolio
    meta.helm.sh/release-namespace: flux-system 
spec:
  interval: 1m
  url: https://github.com/MohanadNasar/Mohanad-Portfolio
  ref:
    branch: main
  secretRef:
    name: git-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mohanad-portfolio
  namespace: flux-system  
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mohanad-portfolio
    meta.helm.sh/release-namespace: flux-system  
spec:
  interval: 5m
  chart:
    spec:
      chart: ./mychart
      sourceRef:
        kind: GitRepository
        name: mohanad-portfolio-dennis
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: mohanadnassar/mohanad-portfolio
      pullPolicy: Always
      tag: latest
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /dennis
      hosts:
        - host: mohanad-portfolio.com
          paths:
            - path: /dennis
              pathType: Prefix
      tls: []
